platform :ios, "7.0"
source 'https://github.com/CocoaPods/Specs.git'

target 'RIGiphyLib_Example', :exclusive => true do
  pod "RIGiphyLib", :path => "../"
  pod 'TMCache'
end

target 'RIGiphyLib_Tests', :exclusive => true do
  pod "RIGiphyLib", :path => "../"  
end
